name: Build and deploy Node.js app to Azure Web App - medrxpa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present --no-watch --no-progress --browsers=ChromeHeadless
          npm run test --if-present
          
      - name: Zip Artifact
        run: zip release.zip ./* -r
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: 'https://medrxpa.azurewebsites.net'  # Update the Azure Web App URL here

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'medrxpa'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D3FE3ED83644C5C93CB20625CEB4A74 }}
          package: .

      # Additional steps for configuring the Azure Web App can be added here if needed

      - name: Update connection strings and links
        run: |
          sed -i 's|{{SQLServerDBConnectionString}}|YOUR_SQL_SERVER_CONNECTION_STRING|' ${{ github.workspace }}/path/to/your/config/file
          sed -i 's|{{mySQLDBConnectionString}}|YOUR_MYSQL_CONNECTION_STRING|' ${{ github.workspace }}/path/to/your/config/file
          sed -i 's|{{hostingProviderForumLink}}|YOUR_FORUM_LINK|' ${{ github.workspace }}/path/to/your/config/file
          sed -i 's|{{controlPanelLink}}|http://windows.azure.com|' ${{ github.workspace }}/path/to/your/config/file
          sed -i 's|{{webSystem}}|WebSites|' ${{ github.workspace }}/path/to/your/config/file

      # Additional steps for post-deployment tasks can be added here if needed
